name: Publish the crate

on:
  release:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish the crate
    runs-on: ubuntu-latest
    steps:
      - uses: https://git.arkforge.net/Mirrors/checkout@v6

      - run: |
          rustup toolchain install 1.94.0
          rustup override set 1.94.0
          rustup show

      - run: cargo publish --token ${CRATES_TOKEN}
        continue-on-error: true
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
