name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    paths:
      - src/docs/**

  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Mirrors/checkout@v6

      - name: Restore cache
        id: cache-cargo-restore
        uses: Mirrors/cache/restore@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-docs-cargo

      - name: Setup MDBook
        continue-on-error: true
        run: |
          MIN_VERSION="0.5.0"
          CURRENT_VERSION=$(mdbook --version | awk '{print $2}' | sed 's/v//')
          if printf '%s\n%s\n' "$MIN_VERSION" "$CURRENT_VERSION" | sort -V -C; then
            echo "mdbook is up-to-date."
          else
            echo "Updating mdbook..."
            cargo install mdbook
          fi

      - name: Save Cache
        id: cache-cargo-save
        uses: Mirrors/cache/save@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-docs-cargo

      - name: Build docs
        run: cd src/docs/latest && mdbook build -d dist

      - name: Copy content to docs
        run: mv src/docs/latest/dist/**/* docs/

      - name: archive content
        run: zip -r docs.zip docs

      - name: upload
        run: bash .forgejo/upload_package.sh "https://internals-yak.arkforge.net" "docs.zip" "{{ secrets.ASTRA_DOCS_SECRET }}" "AstraDocs"
