local TK = {
  NEWLINE = 1,
  INDENT = 2,
  DEDENT = 3,
  IDENTIFIER = 5,
  INTEGER = 6,
  FLOAT = 7,
  STRING = 8,
  PLUS = 9,
  MINUS = 10,
  STAR = 11,
  SLASH = 12,
  DOUBLESLASH = 13,
  PERCENT = 14,
  DOUBLESTAR = 15,
  EQEQ = 16,
  NOTEQ = 17,
  LESS = 18,
  GREATER = 19,
  LESSEQ = 20,
  GREATEREQ = 21,
  EQ = 22,
  PLUSEQ = 23,
  MINUSEQ = 24,
  STAREQ = 25,
  SLASHEQ = 26,
  PERCENTEQ = 27,
  LPAREN = 28,
  RPAREN = 29,
  LBRACKET = 30,
  RBRACKET = 31,
  LBRACE = 32,
  RBRACE = 33,
  COLON = 34,
  COMMA = 35,
  DOT = 36,
  SEMI = 37,
  DEF = 38,
  IF = 39,
  ELIF = 40,
  ELSE = 41,
  WHILE = 42,
  FOR = 43,
  IN = 44,
  RETURN = 45,
  AND = 46,
  OR = 47,
  NOT = 48,
  IS = 49,
  PASS = 50,
  BREAK = 51,
  CONTINUE = 52,
  NONE = 53,
  TRUE = 54,
  FALSE = 55,
  EOF = 56,
  WALRUS = 57,
  ELLIPSIS = 58,
  LAMBDA = 59,
  TRY = 60,
  EXCEPT = 61,
  FINALLY = 62,
  GLOBAL = 63,
  AS = 64,
}

local token_names = {}
for name, id in pairs(TK) do
  token_names[id] = name
end

local keyword_token_map = {
  def = TK.DEF,
  ["if"] = TK.IF,
  elif = TK.ELIF,
  ["else"] = TK.ELSE,
  ["while"] = TK.WHILE,
  ["for"] = TK.FOR,
  ["in"] = TK.IN,
  ["return"] = TK.RETURN,
  ["and"] = TK.AND,
  ["or"] = TK.OR,
  ["not"] = TK.NOT,
  is = TK.IS,
  pass = TK.PASS,
  ["break"] = TK.BREAK,
  continue = TK.CONTINUE,
  None = TK.NONE,
  True = TK.TRUE,
  False = TK.FALSE,
  lambda = TK.LAMBDA,
  ["try"] = TK.TRY,
  ["except"] = TK.EXCEPT,
  ["finally"] = TK.FINALLY,
  ["global"] = TK.GLOBAL,
  ["as"] = TK.AS,
}

local two_character_tokens = {
  ["=="] = TK.EQEQ,
  ["!="] = TK.NOTEQ,
  ["<="] = TK.LESSEQ,
  [">="] = TK.GREATEREQ,
  ["//"] = TK.DOUBLESLASH,
  ["**"] = TK.DOUBLESTAR,
  ["+="] = TK.PLUSEQ,
  ["-="] = TK.MINUSEQ,
  ["*="] = TK.STAREQ,
  ["/="] = TK.SLASHEQ,
  ["%="] = TK.PERCENTEQ,
  [":="] = TK.WALRUS,
  ["..."] = TK.ELLIPSIS,
}

local single_character_tokens = {
  ["+"] = TK.PLUS,
  ["-"] = TK.MINUS,
  ["*"] = TK.STAR,
  ["/"] = TK.SLASH,
  ["%"] = TK.PERCENT,
  ["="] = TK.EQ,
  ["<"] = TK.LESS,
  [">"] = TK.GREATER,
  ["("] = TK.LPAREN,
  [")"] = TK.RPAREN,
  ["["] = TK.LBRACKET,
  ["]"] = TK.RBRACKET,
  ["{"] = TK.LBRACE,
  ["}"] = TK.RBRACE,
  [":"] = TK.COLON,
  [","] = TK.COMMA,
  ["."] = TK.DOT,
  [";"] = TK.SEMI,
}

local multiplicative_operators = {
  [TK.STAR] = true,
  [TK.SLASH] = true,
  [TK.DOUBLESLASH] = true,
  [TK.PERCENT] = true,
}

return {
  TK = TK,
  token_names = token_names,
  keyword_token_map = keyword_token_map,
  two_character_tokens = two_character_tokens,
  single_character_tokens = single_character_tokens,
  multiplicative_operators = multiplicative_operators,
}
