
---@alias tk_kind integer
---@class token_obj: {kind: integer, value: any, line: integer, col: integer}

local TK = {
  NEWLINE = 1,
  INDENT = 2,
  DEDENT = 3,
  IDENTIFIER = 5,
  INTEGER = 6,
  FLOAT = 7,
  STRING = 8,
  PLUS = 9,
  MINUS = 10,
  STAR = 11,
  SLASH = 12,
  DOUBLESLASH = 13,
  PERCENT = 14,
  DOUBLESTAR = 15,
  EQEQ = 16,
  NOTEQ = 17,
  LESS = 18,
  GREATER = 19,
  LESSEQ = 20,
  GREATEREQ = 21,
  EQ = 22,
  PLUSEQ = 23,
  MINUSEQ = 24,
  STAREQ = 25,
  SLASHEQ = 26,
  PERCENTEQ = 27,
  LPAREN = 28,
  RPAREN = 29,
  LBRACKET = 30,
  RBRACKET = 31,
  LBRACE = 32,
  RBRACE = 33,
  COLON = 34,
  COMMA = 35,
  DOT = 36,
  SEMI = 37,
  DEF = 38,
  IF = 39,
  ELIF = 40,
  ELSE = 41,
  WHILE = 42,
  FOR = 43,
  IN = 44,
  RETURN = 45,
  AND = 46,
  OR = 47,
  NOT = 48,
  IS = 49,
  PASS = 50,
  BREAK = 51,
  CONTINUE = 52,
  NONE = 53,
  TRUE = 54,
  FALSE = 55,
  EOF = 56,
  WALRUS = 57,
  ELLIPSIS = 58,
  LAMBDA = 59,
  TRY = 60,
  EXCEPT = 61,
  FINALLY = 62,
  GLOBAL = 63,
  AS = 64,
  CLASS = 65,
  AT = 66,
  COMMENT = 67,
  IMPORT = 68,
  FROM = 69,
  FSTRING_START = 75,
  FSTRING_MIDDLE = 76,
  FSTRING_END = 77,
  FSTRING_EXPR = 78,
  RAISE = 79,
  ASSERT = 80,
  DEL = 81,
  TILDE = 82,
  PIPE = 83,
  AMPERSAND = 84,
  CARET = 85,
  LEFTSHIFT = 86,
  RIGHTSHIFT = 87,
  DOUBLESTAREQ = 88,
  DOUBLESLASHEQ = 89,
  PIPEEQ = 90,
  CARETEQ = 91,
  AMPERSANDEQ = 92,
  LEFTSHIFTEQ = 93,
  RIGHTSHIFTEQ = 94,
  NONLOCAL = 95,
  ASYNC = 96,
  AWAIT = 97,
  WITH = 98,
  YIELD = 99,
}

local token_names = {}
for name, id in pairs(TK) do
  token_names[id] = name
end

local keyword_token_map = {
  def = TK.DEF,
  ["if"] = TK.IF,
  elif = TK.ELIF,
  ["else"] = TK.ELSE,
  ["while"] = TK.WHILE,
  ["for"] = TK.FOR,
  ["in"] = TK.IN,
  ["return"] = TK.RETURN,
  ["and"] = TK.AND,
  ["or"] = TK.OR,
  ["not"] = TK.NOT,
  is = TK.IS,
  pass = TK.PASS,
  ["break"] = TK.BREAK,
  continue = TK.CONTINUE,
  None = TK.NONE,
  True = TK.TRUE,
  False = TK.FALSE,
  lambda = TK.LAMBDA,
  ["try"] = TK.TRY,
  ["except"] = TK.EXCEPT,
  ["finally"] = TK.FINALLY,
  ["global"] = TK.GLOBAL,
  ["as"] = TK.AS,
  ["class"] = TK.CLASS,
  ["import"] = TK.IMPORT,
  ["from"] = TK.FROM,
  ["raise"] = TK.RAISE,
  ["assert"] = TK.ASSERT,
  ["del"] = TK.DEL,
  ["nonlocal"] = TK.NONLOCAL,
  ["async"] = TK.ASYNC,
  ["await"] = TK.AWAIT,
  ["with"] = TK.WITH,
  ["yield"] = TK.YIELD,
}

local multi_character_tokens = {
  ["=="] = TK.EQEQ,
  ["!="] = TK.NOTEQ,
  ["<="] = TK.LESSEQ,
  [">="] = TK.GREATEREQ,
  ["//"] = TK.DOUBLESLASH,
  ["**"] = TK.DOUBLESTAR,
  ["+="] = TK.PLUSEQ,
  ["-="] = TK.MINUSEQ,
  ["*="] = TK.STAREQ,
  ["/="] = TK.SLASHEQ,
  ["%="] = TK.PERCENTEQ,
  [":="] = TK.WALRUS,
  ["..."] = TK.ELLIPSIS,
  ["<<="] = TK.LEFTSHIFTEQ,
  [">>="] = TK.RIGHTSHIFTEQ,
  ["**="] = TK.DOUBLESTAREQ,
  ["//="] = TK.DOUBLESLASHEQ,
  ["|="] = TK.PIPEEQ,
  ["^="] = TK.CARETEQ,
  ["&="] = TK.AMPERSANDEQ,
  ["<<"] = TK.LEFTSHIFT,
  [">>"] = TK.RIGHTSHIFT,
}

local single_character_tokens = {
  ["+"] = TK.PLUS,
  ["-"] = TK.MINUS,
  ["*"] = TK.STAR,
  ["/"] = TK.SLASH,
  ["%"] = TK.PERCENT,
  ["="] = TK.EQ,
  ["<"] = TK.LESS,
  [">"] = TK.GREATER,
  ["("] = TK.LPAREN,
  [")"] = TK.RPAREN,
  ["["] = TK.LBRACKET,
  ["]"] = TK.RBRACKET,
  ["{"] = TK.LBRACE,
  ["}"] = TK.RBRACE,
  [":"] = TK.COLON,
  [","] = TK.COMMA,
  ["."] = TK.DOT,
  [";"] = TK.SEMI,
  ["@"] = TK.AT,
  ["~"] = TK.TILDE,
  ["|"] = TK.PIPE,
  ["&"] = TK.AMPERSAND,
  ["^"] = TK.CARET,
}

local multiplicative_operators = {
  [TK.STAR] = true,
  [TK.SLASH] = true,
  [TK.DOUBLESLASH] = true,
  [TK.PERCENT] = true,
}

return {
  TK = TK,
  token_names = token_names,
  keyword_token_map = keyword_token_map,
  multi_character_tokens = multi_character_tokens,
  single_character_tokens = single_character_tokens,
  multiplicative_operators = multiplicative_operators,
}
