[book]
title = "ArkForge Astra"
authors = ["Elham Aryanpur"]
language = "en"
src = "./src"

[build]
build-dir = "../../../docs"

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"
git-repository-url = "https://git.arkforge.net/ArkForgeLabs/Astra"
site-url = "/"
edit-url-template = "https://git.arkforge.net/ArkForgeLabs/Astra/_edit/main/src/docs/latest/{path}"

[output.html.playground]
copyable = true
copy-js = true
