name: Publish the crate

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish the crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup toolchain install 1.88.0
          rustup override set 1.88.0
          rustup show

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}