name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Full version
          - os: ubuntu-20.04
            name: full luajit release ubuntu-20.04
            flags: --features default
            artifact_name: astra
            asset_name: astra-full-luajit-linux-amd64

          - os: windows-2022
            name: full luajit release windows-2022
            flags: --features default
            artifact_name: astra.exe
            asset_name: astra-full-luajit-windows-amd64.exe

          ## Luau
          - os: ubuntu-20.04
            name: full luau release ubuntu-20.04
            flags: --no-default-features --features luau,utils_luau
            artifact_name: astra
            asset_name: astra-full-luau-linux-amd64

          - os: windows-2022
            name: full luau release windows-2022
            flags: --no-default-features --features luau,utils_luau
            artifact_name: astra.exe
            asset_name: astra-full-luau-windows-amd64.exe
          
          # Core version
          - os: ubuntu-20.04
            name: core luajit release ubuntu-20.04
            flags: "--no-default-features --features luajit"
            artifact_name: astra
            asset_name: astra-core-luajit-linux-amd64

          - os: windows-2022
            name: core luajit release windows-2022
            flags: "--no-default-features --features luajit"
            artifact_name: astra.exe
            asset_name: astra-core-luajit-windows-amd64.exe
          
          # Luau
          - os: ubuntu-20.04
            name: core luau release ubuntu-20.04
            flags: "--no-default-features --features luau"
            artifact_name: astra
            asset_name: astra-core-luau-linux-amd64

          - os: windows-2022
            name: core luau release windows-2022
            flags: "--no-default-features --features luau"
            artifact_name: astra.exe
            asset_name: astra-core-luau-windows-amd64.exe

    name: ${{ matrix.name }}
    runs-on: '${{ matrix.os }}'
    environment: production

    env:
      CARGO_INCREMENTAL: 0
      cache-key: "cargo-cache"

    steps:
      - uses: actions/checkout@v4

      - name: Build Server
        run: cargo build --release ${{ matrix.flags }}

      - name: Upload server binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://github.com/ArkForgeLabs/Astra
          environment: production

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"
