name: Release Windows

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release Windows
    runs-on: windows-latest
    environment: production

    env:
      CARGO_INCREMENTAL: 0

    steps:
      - uses: actions/checkout@v4
      
      - name: Restore cache
        id: cache-cargo-restore
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      
      - run: |
          rustup toolchain install 1.88.0
          rustup override set 1.88.0
          rustup show

      - name: LuaJIT
        run: cargo build --release --features default
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-luajit-windows-amd64.exe
          tag: ${{ github.ref }}

      - name: LuaJIT 52
        run: cargo build --release --no-default-features --features luajit52
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-luajit52-windows-amd64.exe
          tag: ${{ github.ref }}
      
      - name: Luau
        run: cargo build --release --no-default-features --features luau
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-luau-windows-amd64.exe
          tag: ${{ github.ref }}

      - name: Lua 5.1
        run: cargo build --release --no-default-features --features lua51
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-lua51-windows-amd64.exe
          tag: ${{ github.ref }}
      
      - name: Lua 5.2
        run: cargo build --release --no-default-features --features lua52
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-lua52-windows-amd64.exe
          tag: ${{ github.ref }}
      
      - name: Lua 5.3
        run: cargo build --release --no-default-features --features lua53
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-lua53-windows-amd64.exe
          tag: ${{ github.ref }}
      
      - name: Lua 5.4
        run: cargo build --release --no-default-features --features lua54
      - uses: svenstaro/upload-release-action@v2
        with:
          file: ./target/release/astra.exe
          asset_name: astra-lua54-windows-amd64.exe
          tag: ${{ github.ref }}

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: https://github.com/ArkForgeLabs/Astra
          environment: production

      - name: Save Cache
        id: cache-cargo-save
        uses: actions/cache/save@v4
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-cargo

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "success"

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: "failure"
